//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class APIEntityModelContainer : DbContext
    {
        public APIEntityModelContainer()
            : base("name=APIEntityModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TMDB> TMDBSet { get; set; }
        public virtual DbSet<Movies> MoviesSet { get; set; }
        public virtual DbSet<Local> LocalSet { get; set; }
        public virtual DbSet<torrents> torrentsSet { get; set; }
        public virtual DbSet<TMDBgenres> TMDBgenresSet { get; set; }
        public virtual DbSet<YTS> YTSSet { get; set; }
        public virtual DbSet<production_companies> production_companiesSet { get; set; }
        public virtual DbSet<YTSgenres> YTSgenresSet { get; set; }
    }
}
