//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Local
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Year { get; set; }
        public string FileName { get; set; }
        public string Location { get; set; }
        public string Extension { get; set; }
        public string Subtitle { get; set; }
        public string Pixelsize { get; set; }
        public string Format { get; set; }
        public string Formatsize { get; set; }
        public string Group { get; set; }
        public string Error { get; set; }
    }
}
