//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual Movies Movies { get; set; }
        public virtual LogError LogError { get; set; }
        public virtual LogSuccess LogSuccess { get; set; }
        public virtual LogInfo LogInfo { get; set; }
    }
}
